/**
 * @file CalculatorOne 计算器
 * @author Auto Generated by IconSpace
 */

// @ts-nocheck
/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'calculator-one',
    false,
    (createElement: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <rect
                x="8"
                y="4"
                width="32"
                height="40"
                rx="2"
                stroke={props.colors[0]}
                strokeWidth={props.strokeWidth}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
            />
            <rect
                x="14"
                y="11"
                width="20"
                height="9"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                strokeWidth={props.strokeWidth}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
            />
            <circle
                cx="17"
                cy="26"
                r="2"
                fill={props.colors[0]}
            />
            <circle
                cx="17"
                cy="32"
                r="2"
                fill={props.colors[0]}
            />
            <circle
                cx="17"
                cy="38"
                r="2"
                fill={props.colors[0]}
            />
            <circle
                cx="24"
                cy="26"
                r="2"
                fill={props.colors[0]}
            />
            <circle
                cx="24"
                cy="32"
                r="2"
                fill={props.colors[0]}
            />
            <circle
                cx="24"
                cy="38"
                r="2"
                fill={props.colors[0]}
            />
            <circle
                cx="31"
                cy="26"
                r="2"
                fill={props.colors[0]}
            />
            <circle
                cx="31"
                cy="32"
                r="2"
                fill={props.colors[0]}
            />
            <circle
                cx="31"
                cy="38"
                r="2"
                fill={props.colors[0]}
            />
        </svg>
    )
);
