/**
 * @file FileMarkdown 文件-markdown
 * @author Auto Generated by IconSpace
 */

// @ts-nocheck
/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'file-markdown',
    false,
    (createElement: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M10,4H30l10,10v28c0,1.1-.9,2-2,2H10c-1.1,0-2-.9-2-2V6c0-1.1,.9-2,2-2Z"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
            <path
                d="M17,33v-14l7,8.4,7-8.4v14"
                stroke={props.colors[2]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
        </svg>
    )
);
