/**
 * @file Ico ico
 * @author Auto Generated by IconSpace
 */

// @ts-nocheck
/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'ico',
    false,
    (createElement: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <g>
                <g>
                    <path
                        d="M10,38v6h28v-6"
                        stroke={props.colors[0]}
                        strokeLinecap={props.strokeLinecap}
                        strokeLinejoin={props.strokeLinejoin}
                        strokeWidth={props.strokeWidth}
                    />
                    <path
                        d="M38,20v-6L30,4H10V20"
                        stroke={props.colors[0]}
                        strokeLinecap={props.strokeLinecap}
                        strokeLinejoin={props.strokeLinejoin}
                        strokeWidth={props.strokeWidth}
                    />
                    <path
                        d="M28,4V14h10"
                        stroke={props.colors[0]}
                        strokeLinecap={props.strokeLinecap}
                        strokeLinejoin={props.strokeLinejoin}
                        strokeWidth={props.strokeWidth}
                    />
                    <path
                        d="M16,12h4"
                        stroke={props.colors[0]}
                        strokeLinecap={props.strokeLinecap}
                        strokeWidth={props.strokeWidth}
                    />
                    <rect
                        x="4"
                        y="20"
                        width="40"
                        height="18"
                        rx="2"
                        ry="2"
                        stroke={props.colors[0]}
                        strokeLinejoin={props.strokeLinejoin}
                        strokeWidth={props.strokeWidth}
                    />
                </g>
                <line
                    x1="10"
                    y1="25"
                    x2="15"
                    y2="25"
                    stroke={props.colors[0]}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                    strokeWidth={props.strokeWidth}
                />
                <line
                    x1="10"
                    y1="33"
                    x2="15"
                    y2="33"
                    stroke={props.colors[0]}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                    strokeWidth={props.strokeWidth}
                />
                <line
                    x1="12.5"
                    y1="25"
                    x2="12.5"
                    y2="33"
                    stroke={props.colors[0]}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                    strokeWidth={props.strokeWidth}
                />
            </g>
            <polyline
                points="26.5 25 20.5 25 20.5 33 26.5 33"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
            <rect
                x="32"
                y="25"
                width="6"
                height="8"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
        </svg>
    )
);
