/**
 * @file LockingPicture 图片锁定
 * @author Auto Generated by IconSpace
 */

// @ts-nocheck
/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'locking-picture',
    true,
    (createElement: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <g>
                <path
                    d="M6,35l10.7-9.8c.7-.7,1.9-.7,2.7,0l12.7,10.8"
                    stroke={props.colors[0]}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                    strokeWidth={props.strokeWidth}
                />
                <path
                    d="M28,31l4.8-4.8c.7-.7,1.8-.8,2.6-.2l6.6,5"
                    stroke={props.colors[0]}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                    strokeWidth={props.strokeWidth}
                />
            </g>
            <path
                d="M24,6H8.7c-1.5,0-2.7,1.2-2.7,2.7v30.6c0,1.5,1.2,2.7,2.7,2.7h30.6c1.5,0,2.7-1.2,2.7-2.7v-13.3"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
            <path
                d="M36,6c1.7,0,3,1.3,3,3v3h-6v-3c0-1.7,1.3-3,3-3h0Z"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
            <rect
                x="30"
                y="12"
                width="12"
                height="8"
                rx="3"
                ry="3"
                fill={props.colors[1]}
                stroke={props.colors[0]}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
        </svg>
    )
);
