/**
 * @file More 更多
 * @author Auto Generated by IconSpace
 */

// @ts-nocheck
/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'more',
    false,
    (createElement: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <circle
                cx="12"
                cy="24"
                r="3"
                fill={props.colors[0]}
            />
            <circle
                cx="24"
                cy="24"
                r="3"
                fill={props.colors[0]}
            />
            <circle
                cx="36"
                cy="24"
                r="3"
                fill={props.colors[0]}
            />
        </svg>
    )
);
