/**
 * @file Png png
 * @author Auto Generated by IconSpace
 */

// @ts-nocheck
/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'png',
    false,
    (createElement: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <g>
                <path
                    d="M10,38v6h28v-6"
                    stroke={props.colors[0]}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                    strokeWidth={props.strokeWidth}
                />
                <path
                    d="M38,20v-6L30,4H10V20"
                    stroke={props.colors[0]}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                    strokeWidth={props.strokeWidth}
                />
                <path
                    d="M28,4V14h10"
                    stroke={props.colors[0]}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                    strokeWidth={props.strokeWidth}
                />
                <path
                    d="M10,25v8"
                    stroke={props.colors[0]}
                    strokeLinecap={props.strokeLinecap}
                    strokeWidth={props.strokeWidth}
                />
                <path
                    d="M10,25h3.5c1.4,0,2.5,1.1,2.5,2.5h0c0,1.4-1.1,2.5-2.5,2.5h-3.5"
                    stroke={props.colors[0]}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                    strokeWidth={props.strokeWidth}
                />
                <path
                    d="M16,12h4"
                    stroke={props.colors[0]}
                    strokeLinecap={props.strokeLinecap}
                    strokeWidth={props.strokeWidth}
                />
                <rect
                    x="4"
                    y="20"
                    width="40"
                    height="18"
                    rx="2"
                    ry="2"
                    stroke={props.colors[0]}
                    strokeLinejoin={props.strokeLinejoin}
                    strokeWidth={props.strokeWidth}
                />
            </g>
            <polyline
                points="21 33 21 25 27 33 27 25"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
            <polyline
                points="38 25 32 25 32 33 38 33 38 29.5"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
        </svg>
    )
);
