/**
 * @file Refunded 已退款
 * @author Auto Generated by IconSpace
 */

// @ts-nocheck
/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'refunded',
    false,
    (createElement: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <path
                d="M43,22V10c-.1-.6-.3-1.2-.7-1.7-.5-.8-1.4-1.3-2.5-1.3H8c-1.7,0-3,1.3-3,3v28c0,1.7,1.3,3,3,3l19,.2"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
            <path
                d="M14.9,14.8l5,6,5-6"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
            <path
                d="M14,27h12"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
            <path
                d="M14,21h12"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
            <path
                d="M20,21v12"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
            <path
                d="M33,35h10v-7"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
            <path
                d="M34,39l-4-4.2,4-4.2"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
        </svg>
    )
);
