/**
 * @file Svg svg
 * @author Auto Generated by IconSpace
 */

// @ts-nocheck
/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'svg',
    false,
    (createElement: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <g>
                <g>
                    <path
                        d="M10,38v6h28v-6"
                        stroke={props.colors[0]}
                        strokeLinecap={props.strokeLinecap}
                        strokeLinejoin={props.strokeLinejoin}
                        strokeWidth={props.strokeWidth}
                    />
                    <path
                        d="M38,20v-6L30,4H10V20"
                        stroke={props.colors[0]}
                        strokeLinecap={props.strokeLinecap}
                        strokeLinejoin={props.strokeLinejoin}
                        strokeWidth={props.strokeWidth}
                    />
                    <path
                        d="M28,4V14h10"
                        stroke={props.colors[0]}
                        strokeLinecap={props.strokeLinecap}
                        strokeLinejoin={props.strokeLinejoin}
                        strokeWidth={props.strokeWidth}
                    />
                    <path
                        d="M16,12h4"
                        stroke={props.colors[0]}
                        strokeLinecap={props.strokeLinecap}
                        strokeWidth={props.strokeWidth}
                    />
                    <rect
                        x="4"
                        y="20"
                        width="40"
                        height="18"
                        rx="2"
                        ry="2"
                        stroke={props.colors[0]}
                        strokeLinejoin={props.strokeLinejoin}
                        strokeWidth={props.strokeWidth}
                    />
                </g>
                <polyline
                    points="38 25 32 25 32 33 38 33 38 29.5"
                    stroke={props.colors[0]}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                    strokeWidth={props.strokeWidth}
                />
            </g>
            <polyline
                points="20 25 24 33 27 25"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
            <polyline
                points="15.1 25.1 10.1 25 15 33 10 33"
                stroke={props.colors[0]}
                strokeLinecap={props.strokeLinecap}
                strokeLinejoin={props.strokeLinejoin}
                strokeWidth={props.strokeWidth}
            />
        </svg>
    )
);
