/**
 * @file Upload 上传
 * @author Auto Generated by IconSpace
 */

// @ts-nocheck
/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'upload',
    false,
    (createElement: IconHelper, props: ISvgIconProps) => (
        <svg
            width={props.size}
            height={props.size}
            viewBox="0 0 48 48"
            fill="none"
        >
            <mask
                id={props.id + 'a50d0229'}
                maskUnits="userSpaceOnUse"
                x="0"
                y="0"
                width="48"
                height="48" style={{maskType: 'alpha'}}
            >
                <path
                    d="M48 0H0V48H48V0Z"
                    fill={props.colors[2]}
                />
            </mask>
            <g
                mask={'url(#' + props.id + 'a50d0229' + ')'}
            >
                <path
                    d="M6 24.0083V42H42V24"
                    stroke={props.colors[0]}
                    strokeWidth={props.strokeWidth}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                />
                <path
                    d="M33 15L24 6L15 15"
                    stroke={props.colors[0]}
                    strokeWidth={props.strokeWidth}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                />
                <path
                    d="M23.9917 32V6"
                    stroke={props.colors[0]}
                    strokeWidth={props.strokeWidth}
                    strokeLinecap={props.strokeLinecap}
                    strokeLinejoin={props.strokeLinejoin}
                />
            </g>
        </svg>
    )
);
